env:
  es6: true
plugins:
  - prettier
parser: babel-eslint # fixme remove as soon as eslint supports optional chaining https://github.com/eslint/eslint/pull/13416
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  linebreak-style:
    - error
    - unix
  prettier/prettier: error
